CREATE PROCEDURE [dbo].[SpActualizanSeguridadSocial] 
@empresa int,@año int,@mes int,@idTercero int,@IBCsalud int,@IBCpension int,
@IBCarp int,@IBCcaja int,@dSalud int,@dPension int,@dArp int,@dCaja int,@valorSalud int,@valorPension int,
@valorFondo int,@valorFondoSub int,@valorArp int,@valorCaja int,@valorSena int,@valorIcbf int,@IRP int,@pSalud float,
@pPension float,@pArp float,@pCaja float,@pFondo float,@ING varchar(1),@RET varchar(1),@registro int,
@TDE varchar(1),@TAE varchar(1),@TDP varchar(1),@TAP varchar(1),@VSP varchar(1),@VTE varchar(1),
@VST varchar(1),@SLN varchar(1),@IGE varchar(1),@LMA varchar(1),@VAC varchar(1),@AVP varchar(1),@VCT varchar(1),
@exoneraSalud varchar(1),@Retorno int output  AS begin tran nSeguridadSocial 
 update nSeguridadSocial set 
 idTercero = @idTercero,
 IBCsalud = @IBCsalud,
 IBCpension = @IBCpension,
 IBCarp = @IBCarp,
 IBCcaja = @IBCcaja,
 dSalud = @dSalud,
 dPension = @dPension,
 dArp = @dArp,
 dCaja = @dCaja,
 valorSalud = @valorSalud,
 valorPension = @valorPension,
 valorFondo = @valorFondo,
 valorFondoSub = @valorFondoSub,
 valorArp = @valorArp,
 valorCaja = @valorCaja,
 valorSena = @valorSena,
 valorIcbf = @valorIcbf,
 IRP = @IRP,
 pSalud = @pSalud,
 pPension = @pPension,
 pArp = @pArp,
 pCaja = @pCaja,
 pFondo = @pFondo,
 ING = @ING,
 RET = @RET,
 TDE = @TDE,
 TAE = @TAE,
 TDP = @TDP,
 TAP = @TAP,
 VSP = @VSP,
 exoneraSalud=@exoneraSalud,
 AVP=@AVP,
 LMA=@LMA,
 SLN=@SLN,
 VAC=@VAC,
 VCT=@VCT,
 VTE=@VTE,
 VST=@VST

 where año = @año and empresa = @empresa and mes = @mes and registro = @registro 
 if (@@error = 0 ) begin set @Retorno = 0 commit tran nSeguridadSocial end else begin set @Retorno = 1 rollback tran nSeguridadSocial end