 CREATE PROCEDURE [dbo].[SpActualizanSeguridadSocialPila]
 @empresa	int,
@año	int,
@mes	int,
@registro	int,
@idTercero	int,
@codigoTercero	varchar(50),
@apellido1	varchar(50),
@apellido2	varchar(50),
@nombre1	varchar(50),
@nombre2	varchar(50),
@departamento	varchar(50),
@ciudad	varchar(50),
@tipoCotizante	varchar(50),
@subTipoCotizante	varchar(50),
@horasLaboradas	int,
@extranjero	varchar(50),
@RecidenteExterior	varchar(50),
@fechaRadExterior	date,
@ING	varchar(50),
@fechaIngreso	date,
@RET	varchar(50),
@fechaRetiro	date,
@TDE	varchar(50),
@TAE	varchar(50),
@TDP	varchar(50),
@TAP	varchar(50),
@VSP	varchar(50),
@fechaVSP	date,
@VST	varchar(50),
@SLN	varchar(50),
@fiSLN	date,
@ffSLN	date,
@IGE	varchar(50),
@fiIGE	date,
@ffIGE	date,
@LMA	varchar(50),
@fiLMA	date,
@ffLMA	date,
@VAC	varchar(50),
@fiVAC	date,
@ffVAC	date,
@AVP	varchar(50),
@VCT	varchar(50),
@fiVCT	date,
@ffVCT	date,
@IRL	int,
@fiIRL	date,
@ffIRL	date,
@correciones	varchar(50),
@salario	int,
@salarioIntegral	varchar(50),
@terceroPension	int,
@dPension	int,
@IBCpension	int,
@pPension	float,
@valorPension	int,
@indicadorAltoRiesgo	varchar(50),
@cotizacionVoluntariaAfiliado	float,
@cotizacionVoluntariaEmpleador	float,
@valorFondo	float,
@valorFondoSub	float,
@pFondo	float,
@valorRetenido	float,
@totalPension	float,
@AFPdestino	varchar(50),
@terceroSalud	int,
@dSalud	int,
@IBCsalud	int,
@pSalud	float,
@valorSalud	float,
@valorUPC	float,
@noAutorizacionEG	varchar(50),
@valorIncapacidad	float,
@noAutorizacionLMA	varchar(50),
@valorLMA	float,
@saludDestino	nchar,
@terceroArl	int,
@dArl	int,
@IBCarl	int,
@pArl	float,
@claseARL	int,
@centroTrabajo	varchar(50),
@valorArl	float,
@dCaja	int,
@terceroCaja	int,
@IBCcaja	int,
@pCaja	float,
@valorCaja	int,
@IBCCajaOtros	float,
@pSena	float,
@valorSena	int,
@terceroSena	int,
@pICBF	float,
@valorICBF	int,
@terceroIcbf	int,
@pESAP	float,
@valorESAP	float,
@pMEN	float,
@valorMEN	float,
@exoneraSalud	varchar(50),
@tipoIDcotizanteUPC	varchar(50),
@noIDcotizanteUPC	varchar(50),
@contrato int,
@tipoID varchar(50),
@Retorno int output  
AS begin tran nSeguridadSocialPila

DECLARE @FECHAVALOR DATE ='01/01/1990'

IF (@fechaIngreso=@FECHAVALOR)
	SET @fechaIngreso=NULL
IF (@fechaRadExterior=@FECHAVALOR)
	SET @fechaRadExterior=NULL
IF (@fechaRetiro=@FECHAVALOR)
	SET @fechaRetiro=NULL
IF (@fechaVSP=@FECHAVALOR)
	SET @fechaVSP=NULL
IF (@ffIGE=@FECHAVALOR)
	SET @ffIGE=NULL
IF (@ffIRL=@FECHAVALOR)
	SET @ffIRL=NULL
IF (@ffLMA=@FECHAVALOR)
	SET @ffLMA=NULL
IF (@ffSLN=@FECHAVALOR)
	SET @ffSLN=NULL
IF (@ffVAC=@FECHAVALOR)
	SET @ffVAC=NULL
IF (@ffVCT=@FECHAVALOR)
	SET @ffVCT=NULL
IF (@fiIGE=@FECHAVALOR)
	SET @fiIGE=NULL
IF (@fiIRL=@FECHAVALOR)
	SET @fiIRL=NULL
IF (@fiLMA=@FECHAVALOR)
	SET @fiLMA=NULL
IF (@fiSLN=@FECHAVALOR)
	SET @fiSLN=NULL
IF (@fiVAC=@FECHAVALOR)
	SET @fiVAC=NULL
IF (@fiVCT=@FECHAVALOR)
	SET @fiVCT=NULL

 update nSeguridadSocialPila 
set 
idTercero=@idTercero,
codigoTercero=@codigoTercero,
apellido1=@apellido1,
apellido2=@apellido2,
nombre1=@nombre1,
nombre2=@nombre2,
departamento=@departamento,
ciudad=@ciudad,
tipoCotizante=@tipoCotizante,
subTipoCotizante=@subTipoCotizante,
horasLaboradas=@horasLaboradas,
extranjero=@extranjero,
RecidenteExterior=@RecidenteExterior,
fechaRadExterior=@fechaRadExterior,
ING=@ING,
fechaIngreso=@fechaIngreso,
RET=@RET,
fechaRetiro=@fechaRetiro,
TDE=@TDE,
TAE=@TAE,
TDP=@TDP,
TAP=@TAP,
VSP=@VSP,
fechaVSP=@fechaVSP,
VST=@VST,
SLN=@SLN,
fiSLN=@fiSLN,
ffSLN=@ffSLN,
IGE=@IGE,
fiIGE=@fiIGE,
ffIGE=@ffIGE,
LMA=@LMA,
fiLMA=@fiLMA,
ffLMA=@ffLMA,
VAC=@VAC,
fiVAC=@fiVAC,
ffVAC=@ffVAC,
AVP=@AVP,
VCT=@VCT,
fiVCT=@fiVCT,
ffVCT=@ffVCT,
IRL=@IRL,
fiIRL=@fiIRL,
ffIRL=@ffIRL,
correciones=@correciones,
salario=@salario,
salarioIntegral=@salarioIntegral,
terceroPension=@terceroPension,
dPension=@dPension,
IBCpension=@IBCpension,
pPension=@pPension,
valorPension=@valorPension,
indicadorAltoRiesgo=@indicadorAltoRiesgo,
cotizacionVoluntariaAfiliado=@cotizacionVoluntariaAfiliado,
cotizacionVoluntariaEmpleador=@cotizacionVoluntariaEmpleador,
valorFondo=@valorFondo,
valorFondoSub=@valorFondoSub,
pFondo=@pFondo,
valorRetenido=@valorRetenido,
totalPension=@totalPension,
AFPdestino=@AFPdestino,
terceroSalud=@terceroSalud,
dSalud=@dSalud,
IBCsalud=@IBCsalud,
pSalud=@pSalud,
valorSalud=@valorSalud,
valorUPC=@valorUPC,
noAutorizacionEG=@noAutorizacionEG,
valorIncapacidad=@valorIncapacidad,
noAutorizacionLMA=@noAutorizacionLMA,
valorLMA=@valorLMA,
saludDestino=@saludDestino,
terceroArl=@terceroArl,
dArl=@dArl,
IBCarl=@IBCarl,
pArl=@pArl,
claseARL=@claseARL,
centroTrabajo=@centroTrabajo,
valorArl=@valorArl,
dCaja=@dCaja,
terceroCaja=@terceroCaja,
IBCcaja=@IBCcaja,
pCaja=@pCaja,
valorCaja=@valorCaja,
IBCCajaOtros=@IBCCajaOtros,
pSena=@pSena,
valorSena=@valorSena,
terceroSena=@terceroSena,
pICBF=@pICBF,
valorICBF=@valorICBF,
terceroIcbf=@terceroIcbf,
pESAP=@pESAP,
valorESAP=@valorESAP,
pMEN=@pMEN,
valorMEN=@valorMEN,
exoneraSalud=@exoneraSalud,
tipoIDcotizanteUPC=@tipoIDcotizanteUPC,
noIDcotizanteUPC=@noIDcotizanteUPC,
contrato=@contrato,
tipoID=@tipoID
where año = @año and empresa = @empresa and mes = @mes and registro = @registro 
if (@@error = 0 ) begin set @Retorno = 0 commit tran nSeguridadSocialPila end else begin set @Retorno = 1 rollback tran nSeguridadSocialPila end