
CREATE proc [dbo].[spActualizanContratos]
@empresa     int    ,
@id    int,
@codigoTercero      varchar(50), 
@tercero     int,
@cargo varchar(50), 
@banco varchar(50), 
@tipoContizante     varchar(50), 
@motivoRetiro varchar(50), 
@turno varchar(50), 
@departamento varchar(50), 
@ccosto      varchar(50), 
@tipoNomina  varchar(50), 
@tiempoBasico varchar(50), 
@entidadPension     varchar(50), 
@entidadEps  varchar(50), 
@entidadCesantias   varchar(50), 
@entidadCaja varchar(50), 
@entidadArp  varchar(50), 
@entidadSena varchar(50), 
@entidadIcbf varchar(50), 
@fechaIngreso datetime,    
@fechaRetiro datetime,    
@fechaContratoHasta datetime,    
@fechaPrimaHasta    datetime,    
@fechaVacacionesHasta      datetime,    
@fechaUltimoAumento datetime,    
@fechaUltimoVacaciones     datetime,    
@fechaUltimaPension datetime,    
@fechaUltimoCesantias      datetime,    
@salario     money, 
@salarioAnterior    money, 
@valorDeducibleRete money, 
@valorCesantiasCongeladas  money, 
@valorCesantiasRetiradas   money, 
@valorOtrosSalud    money, 
@valorSaludObligatoria     money, 
@cantidadHoras      decimal(9, 6),      
@pRetencion  decimal(9, 6),      
@pTiempoLaborado    decimal(9, 6),      
@diasPagadosVaciones decimal(9, 6),      
@personaCargo int,
@cuentaBancaria     varchar(50), 
@formaPago   varchar(50), 
@regimenLaboral     int,
@auxilioTransporte  int    ,
@procediimentoRete  int    ,
@pactoColectivo     varchar(50), 
@deducible   varchar(50), 
@otrosSalud  varchar(50), 
@salarioIntegral    bit    ,
@tipoCuenta  varchar(50), 
@claseContrato      varchar(10)   ,
@terminoContrato    varchar(1)   ,
@foto  int    ,
@observacion varchar(50), 
@activo      bit    ,
@valorPrepagada     money, 
@valorDependientes  money, 
@fechaRegistro      datetime,    
@usuario     varchar(50), 
@fechaActualizacion datetime,    
@usuarioActualizacion      varchar(50),
@fechaContratoLey50 datetime,
@ley50 bit,
@centroTrabajo varchar(50),
@subTipoCotizante varchar(50),
@diasContrato int,
@mSindicato bit,	@mFondoEmpleado bit,	@entidadFondoEmpleado varchar(50),	
@entidadSindicato varchar(50),	@pFondoEmpleado float,	@pSindicato float,
@entidadSaludAdicional varchar(50),
@manejaDestajo bit,@cantidadDestajo int,@grupolaborDestajo varchar(50),
@Retorno int output  AS 

begin tran nContratos

if (select fechaRetiro from nContratos where empresa = @empresa and id = @id and codigoTercero = @codigoTercero and tercero = @tercero ) is not null 
	set @fechaRetiro=@fechaContratoHasta

update  nContratos
set 
cargo         = @cargo        ,
banco         = @banco        ,
tipoContizante             = @tipoContizante            ,
motivoRetiro        = @motivoRetiro       ,
turno         = @turno        ,
departamento        = @departamento       ,
ccosto        = @ccosto       ,
tipoNomina          = @tipoNomina         ,
tiempoBasico        = @tiempoBasico       ,
entidadPension             = @entidadPension            ,
entidadEps          = @entidadEps         ,
entidadCesantias           = @entidadCesantias          ,
entidadCaja         = @entidadCaja        ,
entidadArp          = @entidadArp         ,
entidadSena         = @entidadSena        ,
entidadIcbf         = @entidadIcbf        ,
fechaIngreso        = @fechaIngreso       ,
fechaRetiro         = @fechaRetiro        ,
fechaContratoHasta         = @fechaContratoHasta        ,
fechaPrimaHasta            = @fechaPrimaHasta           ,
fechaVacacionesHasta        = @fechaVacacionesHasta       ,
fechaUltimoAumento         = @fechaUltimoAumento        ,
fechaUltimoVacaciones             = @fechaUltimoVacaciones            ,
fechaUltimaPension         = @fechaUltimaPension        ,
fechaUltimoCesantias        = @fechaUltimoCesantias       ,
salario             = @salario            ,
salarioAnterior            = @salarioAnterior           ,
valorDeducibleRete         = @valorDeducibleRete        ,
valorCesantiasCongeladas          = @valorCesantiasCongeladas         ,
valorCesantiasRetiradas           = @valorCesantiasRetiradas          ,
valorOtrosSalud            = @valorOtrosSalud           ,
valorSaludObligatoria             = @valorSaludObligatoria            ,
cantidadHoras        = @cantidadHoras       ,
pRetencion          = @pRetencion         ,
pTiempoLaborado            = @pTiempoLaborado           ,
diasPagadosVaciones        = @diasPagadosVaciones       ,
personaCargo  = @personaCargo ,
cuentaBancaria             = @cuentaBancaria            ,
formaPago           = @formaPago          ,
regimenLaboral       = @regimenLaboral      ,
auxilioTransporte           = @auxilioTransporte          ,
procediimentoRete           = @procediimentoRete          ,
pactoColectivo             = @pactoColectivo            ,
deducible           = @deducible          ,
otrosSalud          = @otrosSalud         ,
salarioIntegral      = @salarioIntegral     ,
tipoCuenta          = @tipoCuenta         ,
claseContrato  = @claseContrato ,
terminoContrato      = @terminoContrato     ,
foto          = @foto         ,
observacion         = @observacion        ,
activo        = @activo       ,
valorPrepagada             = @valorPrepagada            ,
valorDependientes          = @valorDependientes         ,
fechaRegistro        = @fechaRegistro       ,
usuario             = @usuario            ,
fechaActualizacion         = @fechaActualizacion        ,
usuarioActualizacion  = @usuarioActualizacion ,
fechaContratoLey50 = @fechaContratoLey50,
ley50 = @ley50,
centroTrabajo = @centroTrabajo,
diasContrato = @diasContrato,
mSindicato=@mSindicato,	mFondoEmpleado=@mFondoEmpleado,
	entidadFondoEmpleado=@entidadFondoEmpleado,
		entidadSindicato=@entidadSindicato,
			pFondoEmpleado=@pFondoEmpleado,	pSindicato=@pSindicato,
subTipoCotizante=@subTipoCotizante,
entidadSaludAdicional=@entidadSaludAdicional,
manejaDestajo=@manejaDestajo,
cantidadDestajo=@cantidadDestajo,
grupoLaborDestajo=@grupolaborDestajo
where 
empresa             = @empresa            and
id      = @id     and
codigoTercero        = @codigoTercero       and
tercero       = @tercero    
  


if (@@error = 0 ) begin set
@Retorno = 0 
 commit tran nContratos
  end else begin
  set  @Retorno = 1
   rollback tran nContratos end