CREATE TABLE [dbo].[nEmbargos] (
    [empresa]              INT             NOT NULL,
    [empleado]             INT             NOT NULL,
    [codigo]               INT             NOT NULL,
    [tipo]                 VARCHAR (50)    NOT NULL,
    [año]                  INT             NOT NULL,
    [mes]                  INT             NOT NULL,
    [mandamiento]          VARCHAR (50)    NOT NULL,
    [fecha]                DATETIME        NOT NULL,
    [periodoInicial]       VARCHAR (6)     NOT NULL,
    [peridoFinal]          VARCHAR (6)     NULL,
    [saldoCuotas]          INT             NOT NULL,
    [valorCuotas]          MONEY           NOT NULL,
    [porcentaje]           MONEY           NOT NULL,
    [empresaEmbarga]       INT             NULL,
    [embargante]           INT             NULL,
    [valorFinal]           MONEY           NULL,
    [pCobroPosterior]      DECIMAL (18, 2) NULL,
    [cuotasCobroPosterior] INT             NULL,
    [valorCobroPosterior]  MONEY           NULL,
    [valorBase]            MONEY           NOT NULL,
    [saldo]                MONEY           NULL,
    [usuario]              VARCHAR (50)    NOT NULL,
    [fechaRegistro]        DATETIME        NOT NULL,
    [tipoCuenta]           VARCHAR (50)    NOT NULL,
    [banco]                VARCHAR (50)    NOT NULL,
    [cuentaBancaria]       VARCHAR (50)    NOT NULL,
    [modoPago]             VARCHAR (50)    NOT NULL,
    [activo]               BIT             NOT NULL,
    [cobroPosterior]       BIT             NOT NULL,
    [manejaCuota]          BIT             NOT NULL,
    [manejaCuotaPosterior] BIT             NOT NULL,
    [manejaSaldo]          BIT             NOT NULL,
    [valorFinalPosterior]  MONEY           NOT NULL,
    [cuotas]               INT             NOT NULL,
    [fiscal]               VARCHAR (200)   NULL,
    [añoInicial]           INT             NULL,
    [salarioMinimo]        BIT             CONSTRAINT [DF_nEmbargos_salarioMinimo] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_nEmbargos_1] PRIMARY KEY CLUSTERED ([empresa] ASC, [empleado] ASC, [codigo] ASC, [tipo] ASC)
);

