CREATE TABLE [dbo].[aLotes] (
    [empresa]          INT             NOT NULL,
    [codigo]           VARCHAR (50)    NOT NULL,
    [manejaSeccion]    BIT             CONSTRAINT [DF_aLotes_manejaSeccion] DEFAULT ((0)) NOT NULL,
    [seccion]          VARCHAR (50)    NULL,
    [finca]            VARCHAR (50)    NOT NULL,
    [descripcion]      VARCHAR (550)   NOT NULL,
    [añoSiembra]       INT             NOT NULL,
    [mesSiembra]       INT             NOT NULL,
    [palmasBrutas]     INT             NOT NULL,
    [palmasProduccion] INT             NOT NULL,
    [hBrutas]          DECIMAL (18, 2) CONSTRAINT [DF_aLotes_hBrutas] DEFAULT ((0)) NOT NULL,
    [hNetas]           DECIMAL (18, 2) CONSTRAINT [DF_aLotes_hNetas] DEFAULT ((0)) NOT NULL,
    [dSiembra]         DECIMAL (18, 2) CONSTRAINT [DF_aLotes_dSiembra] DEFAULT ((0)) NOT NULL,
    [variedad]         CHAR (5)        NOT NULL,
    [densidad]         DECIMAL (18, 2) CONSTRAINT [DF_aLotes_dencidad] DEFAULT ((0)) NOT NULL,
    [NoLineas]         INT             NOT NULL,
    [fechaRegistro]    DATETIME        NOT NULL,
    [usuario]          VARCHAR (50)    NOT NULL,
    [foto]             VARCHAR (1550)  NULL,
    [activo]           BIT             CONSTRAINT [DF_aLotes_activo] DEFAULT ((0)) NOT NULL,
    [desarrollo]       BIT             CONSTRAINT [DF_aLotes_desarrollo] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_aLotes] PRIMARY KEY CLUSTERED ([empresa] ASC, [codigo] ASC),
    CONSTRAINT [FK_aLotes_aFinca] FOREIGN KEY ([empresa], [finca]) REFERENCES [dbo].[aFinca] ([empresa], [codigo]),
    CONSTRAINT [FK_aLotes_aSecciones] FOREIGN KEY ([empresa], [finca], [seccion]) REFERENCES [dbo].[aSecciones] ([empresa], [finca], [codigo]),
    CONSTRAINT [FK_aLotes_aVariedad] FOREIGN KEY ([empresa], [variedad]) REFERENCES [dbo].[aVariedad] ([empresa], [codigo]),
    CONSTRAINT [FK_aLotes_gEmpresa] FOREIGN KEY ([empresa]) REFERENCES [dbo].[gEmpresa] ([id])
);

