CREATE TABLE [dbo].[aNovedad] (
    [empresa]              INT           NOT NULL,
    [codigo]               VARCHAR (50)  NOT NULL,
    [descripcion]          VARCHAR (200) NOT NULL,
    [desCorta]             VARCHAR (50)  NOT NULL,
    [grupo]                VARCHAR (50)  NOT NULL,
    [uMedida]              VARCHAR (50)  NOT NULL,
    [ciclos]               INT           NOT NULL,
    [tarea]                INT           NOT NULL,
    [naturaleza]           INT           NOT NULL,
    [impuesto]             BIT           NOT NULL,
    [equivalencia]         VARCHAR (50)  NULL,
    [concepto]             VARCHAR (50)  NULL,
    [grupoIR]              CHAR (5)      NULL,
    [manejaLote]           BIT           CONSTRAINT [DF_aNovedad_manejaLote] DEFAULT ((0)) NOT NULL,
    [manejaSaldo]          BIT           CONSTRAINT [DF_aNovedad_manejaSaldo] DEFAULT ((0)) NOT NULL,
    [manejaCanal]          BIT           CONSTRAINT [DF_aNovedad_manejaCanal] DEFAULT ((0)) NOT NULL,
    [manejaLinea]          BIT           CONSTRAINT [DF_aNovedad_manejaLinea] DEFAULT ((0)) NOT NULL,
    [manejaPalma]          BIT           CONSTRAINT [DF_aNovedad_manejaPalma] DEFAULT ((0)) NOT NULL,
    [tipoCanal]            VARCHAR (10)  NULL,
    [manejaRacimo]         BIT           CONSTRAINT [DF_aNovedad_manejaRacimo] DEFAULT ((0)) NOT NULL,
    [manejaJornal]         BIT           CONSTRAINT [DF_aNovedad_manejaJornal] DEFAULT ((0)) NOT NULL,
    [porHaNeta]            BIT           CONSTRAINT [DF_aNovedad_porHaNeta] DEFAULT ((0)) NOT NULL,
    [porHaBruta]           BIT           CONSTRAINT [DF_aNovedad_porHaBruta] DEFAULT ((0)) NOT NULL,
    [porHaProduccion]      BIT           CONSTRAINT [DF_aNovedad_porHaProduccion] DEFAULT ((0)) NOT NULL,
    [manejaBascula]        BIT           CONSTRAINT [DF_aNovedad_bascula] DEFAULT ((0)) NOT NULL,
    [manejaFecha]          BIT           CONSTRAINT [DF_aNovedad_manejaFecha] DEFAULT ((0)) NOT NULL,
    [manejaRango]          BIT           CONSTRAINT [DF_aNovedad_manejaRango] DEFAULT ((0)) NOT NULL,
    [añoDesde]             INT           NULL,
    [añoHasta]             INT           NULL,
    [activo]               BIT           CONSTRAINT [DF_aLabor_activa] DEFAULT ((0)) NOT NULL,
    [fechaRegistro]        DATETIME      NOT NULL,
    [usuario]              VARCHAR (50)  NOT NULL,
    [claseLabor]           INT           NULL,
    [manejaDecimal]        BIT           NOT NULL,
    [noPrestacional]       BIT           CONSTRAINT [DF_aNovedad_noPrestacional] DEFAULT ((0)) NOT NULL,
    [manejaCaracteristica] BIT           CONSTRAINT [DF_aNovedad_manejaCaracteristica] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_aLabores] PRIMARY KEY CLUSTERED ([empresa] ASC, [codigo] ASC),
    CONSTRAINT [FK_aNovedad_aGrupoNovedad] FOREIGN KEY ([empresa], [grupo]) REFERENCES [dbo].[aGrupoNovedad] ([empresa], [codigo]),
    CONSTRAINT [FK_aNovedad_aTipoCanal] FOREIGN KEY ([empresa], [tipoCanal]) REFERENCES [dbo].[aTipoCanal] ([empresa], [codigo]),
    CONSTRAINT [FK_aNovedad_gEmpresa] FOREIGN KEY ([empresa]) REFERENCES [dbo].[gEmpresa] ([id]),
    CONSTRAINT [FK_aNovedad_gUnidadMedida] FOREIGN KEY ([empresa], [uMedida]) REFERENCES [dbo].[gUnidadMedida] ([empresa], [codigo])
);

