CREATE TABLE [dbo].[cContabilizacionDetalle] (
    [empresa]                INT          NOT NULL,
    [tipo]                   VARCHAR (50) NOT NULL,
    [numero]                 VARCHAR (50) NOT NULL,
    [tipoLiquidacion]        VARCHAR (50) NOT NULL,
    [año]                    INT          NOT NULL,
    [mes]                    INT          NOT NULL,
    [periodoContable]        VARCHAR (50) NOT NULL,
    [registro]               INT          NOT NULL,
    [codigoEmpleado]         INT          NOT NULL,
    [identificacionEmpleado] VARCHAR (50) NOT NULL,
    [tipoNomina]             VARCHAR (50) NULL,
    [docNomina]              VARCHAR (50) NULL,
    [contrato]               INT          NOT NULL,
    [periodoNomina]          VARCHAR (50) NULL,
    [claseContrato]          VARCHAR (50) NULL,
    [manejaLabCam]           BIT          NULL,
    [manejaHE]               BIT          NULL,
    [mCcostoNomina]          VARCHAR (50) NULL,
    [aCcostoNomina]          VARCHAR (50) NULL,
    [departamento]           VARCHAR (50) NULL,
    [codigoConcepto]         VARCHAR (50) NOT NULL,
    [codigoLabor]            VARCHAR (50) NULL,
    [cuentaContable]         VARCHAR (50) NULL,
    [mCcostoContable]        VARCHAR (50) NULL,
    [aCcostoContable]        VARCHAR (50) NULL,
    [terceroContable]        VARCHAR (50) NULL,
    [debito]                 FLOAT (53)   NULL,
    [credito]                FLOAT (53)   NULL,
    [entidadSalud]           VARCHAR (50) NULL,
    [entidadPension]         VARCHAR (50) NULL,
    [entidadArl]             VARCHAR (50) NULL,
    [entidadCaja]            VARCHAR (50) NULL,
    [entidadSena]            VARCHAR (50) NULL,
    [entidadCesantias]       VARCHAR (50) NULL,
    [EntidadFsolidaridad]    VARCHAR (50) NULL,
    [EntidadICBF]            VARCHAR (50) NULL,
    [EntidadAdicional]       VARCHAR (50) NULL,
    [mCcostoLote]            VARCHAR (50) NULL,
    [aCcostoLote]            VARCHAR (50) NULL,
    [LoteDesarrollo]         BIT          NULL,
    [baseCesantias]          BIT          CONSTRAINT [DF_cContabilizacion_baseCesantias] DEFAULT ((0)) NULL,
    [basePrimas]             BIT          CONSTRAINT [DF_cContabilizacion_basePrimas] DEFAULT ((0)) NULL,
    [baseIntereses]          BIT          CONSTRAINT [DF_cContabilizacion_baseIntereses] DEFAULT ((0)) NULL,
    [baseVacaciones]         BIT          CONSTRAINT [DF_cContabilizacion_baseVacaciones] DEFAULT ((0)) NULL,
    [baseEmbargos]           BIT          CONSTRAINT [DF_cContabilizacion_baseEmbargos] DEFAULT ((0)) NULL,
    [baseCajaCompensacion]   BIT          CONSTRAINT [DF_cContabilizacion_baseCajaCompensacion] DEFAULT ((0)) NULL,
    [baseSeguridadSocial]    BIT          CONSTRAINT [DF_cContabilizacion_baseSeguridadSocial] DEFAULT ((0)) NULL,
    [tipoConcepto]           VARCHAR (50) NULL,
    [conceptoReferencia]     VARCHAR (50) NULL,
    [estado]                 INT          NOT NULL,
    [fecha]                  DATETIME     NOT NULL,
    [fechaRegistro]          DATETIME     NOT NULL,
    [usuarioRegistro]        VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_cContabilizacion] PRIMARY KEY CLUSTERED ([empresa] ASC, [tipo] ASC, [numero] ASC, [tipoLiquidacion] ASC, [año] ASC, [mes] ASC, [periodoContable] ASC, [registro] ASC)
);

