CREATE TABLE [dbo].[cParametroContaNomi] (
    [empresa]            INT             NOT NULL,
    [id]                 INT             NOT NULL,
    [tipo]               VARCHAR (50)    NOT NULL,
    [clase]              VARCHAR (50)    NOT NULL,
    [tipoTransaccion]    VARCHAR (50)    NOT NULL,
    [cCostoMayor]        VARCHAR (50)    NOT NULL,
    [cCosto]             VARCHAR (50)    NOT NULL,
    [departamento]       VARCHAR (50)    NULL,
    [concepto]           VARCHAR (50)    NULL,
    [manejaEntidad]      BIT             NULL,
    [cuentaActivo]       VARCHAR (50)    NULL,
    [cuentaGasto]        VARCHAR (50)    NULL,
    [cuentaContratista]  VARCHAR (50)    NULL,
    [cCostoMayorSigo]    VARCHAR (50)    NULL,
    [cCostoSigo]         VARCHAR (50)    NULL,
    [cuentaCredito]      VARCHAR (50)    NULL,
    [cCostoMayorCredito] VARCHAR (50)    NULL,
    [cCostoCredito]      VARCHAR (50)    NULL,
    [tipoDato]           INT             NULL,
    [valorTipoDato]      DECIMAL (18, 3) NULL,
    [entidad]            VARCHAR (50)    NULL,
    [labor]              BIT             NULL,
    [tercero]            VARCHAR (50)    NULL,
    [terceroCredito]     VARCHAR (50)    NULL,
    CONSTRAINT [PK_cParametroContaNomi] PRIMARY KEY CLUSTERED ([empresa] ASC, [id] ASC)
);

