CREATE TABLE [dbo].[cTercero] (
    [empresa]       INT           NOT NULL,
    [id]            INT           NOT NULL,
    [codigo]        VARCHAR (50)  NOT NULL,
    [tipoDocumento] CHAR (3)      NOT NULL,
    [tipo]          INT           NOT NULL,
    [nit]           VARCHAR (25)  NOT NULL,
    [dv]            CHAR (3)      NULL,
    [razonSocial]   VARCHAR (550) NOT NULL,
    [apellido1]     VARCHAR (250) NOT NULL,
    [apellido2]     VARCHAR (250) NOT NULL,
    [nombre1]       VARCHAR (550) NOT NULL,
    [nombre2]       VARCHAR (250) NOT NULL,
    [descripcion]   VARCHAR (950) NOT NULL,
    [activo]        BIT           NOT NULL,
    [ciudad]        VARCHAR (50)  NULL,
    [cliente]       BIT           NOT NULL,
    [proveedor]     BIT           NOT NULL,
    [empleado]      BIT           NOT NULL,
    [accionista]    BIT           NOT NULL,
    [contratista]   BIT           CONSTRAINT [DF_cTercero_contratista] DEFAULT ((0)) NOT NULL,
    [extractora]    BIT           NOT NULL,
    [foto]          INT           NULL,
    [contacto]      VARCHAR (550) NULL,
    [fechaRegistro] DATETIME      NOT NULL,
    [telefono]      VARCHAR (50)  NULL,
    [direccion]     VARCHAR (550) NULL,
    [barrio]        VARCHAR (550) NULL,
    [fax]           VARCHAR (50)  NULL,
    [email]         VARCHAR (250) NULL,
    CONSTRAINT [PK_cTercero] PRIMARY KEY CLUSTERED ([empresa] ASC, [id] ASC),
    CONSTRAINT [FK_cTercero_gCiudad] FOREIGN KEY ([empresa], [ciudad]) REFERENCES [dbo].[gCiudad] ([empresa], [codigo]),
    CONSTRAINT [FK_cTercero_gEmpresa] FOREIGN KEY ([empresa]) REFERENCES [dbo].[gEmpresa] ([id])
);

