CREATE TABLE [dbo].[gTipoTransaccionConfig] (
    [empresa]                INT           NOT NULL,
    [tipoTransaccion]        VARCHAR (50)  NOT NULL,
    [ajuste]                 BIT           CONSTRAINT [DF_gTipoTransaccionConfig_ajuste_1] DEFAULT ((0)) NOT NULL,
    [nivelDestino]           INT           NOT NULL,
    [salida]                 BIT           CONSTRAINT [DF_gTipoTransaccionConfig_salida_1] DEFAULT ((0)) NOT NULL,
    [validaSaldo]            BIT           CONSTRAINT [DF_gTipoTransaccionConfig_validaSaldo_1] DEFAULT ((0)) NOT NULL,
    [manejaTalonario]        BIT           CONSTRAINT [DF_gTipoTransaccionConfig_manejaTalonario_1] DEFAULT ((0)) NOT NULL,
    [referenciaTercero]      BIT           CONSTRAINT [DF_gTipoTransaccionConfig_referenciaTercero_1] DEFAULT ((0)) NOT NULL,
    [formatoImpresion]       VARCHAR (250) NOT NULL,
    [dsReferenciaDetalle]    VARCHAR (250) NOT NULL,
    [cantidadEditable]       BIT           CONSTRAINT [DF_gTipoTransaccionConfig_cantidadEditable_1] DEFAULT ((0)) NOT NULL,
    [vUnitarioEditable]      BIT           CONSTRAINT [DF_gTipoTransaccionConfig_vUnitarioEditable_1] DEFAULT ((0)) NOT NULL,
    [pIvaEditable]           BIT           CONSTRAINT [DF_gTipoTransaccionConfig_pIvaEditable_1] DEFAULT ((0)) NOT NULL,
    [manejaBodega]           BIT           CONSTRAINT [DF_gTipoTransaccionConfig_manejaBodega_1] DEFAULT ((0)) NOT NULL,
    [liberaReferencia]       BIT           CONSTRAINT [DF_gTipoTransaccionConfig_liberaReferencia_1] DEFAULT ((0)) NOT NULL,
    [entradaDirecta]         BIT           CONSTRAINT [DF_gTipoTransaccionConfig_entradaDirecta_1] DEFAULT ((0)) NOT NULL,
    [registroDirecto]        BIT           CONSTRAINT [DF_gTipoTransaccionConfig_registroDirecto_1] DEFAULT ((0)) NOT NULL,
    [consignacion]           BIT           CONSTRAINT [DF_gTipoTransaccionConfig_consignacion_1] DEFAULT ((0)) NOT NULL,
    [diaSemana]              BIT           CONSTRAINT [DF_gTipoTransaccionConfig_diaSemana_1] DEFAULT ((0)) NOT NULL,
    [manejaDocumento]        BIT           CONSTRAINT [DF_gTipoTransaccionConfig_manejaDocumento_1] DEFAULT ((0)) NOT NULL,
    [vigencia]               BIT           CONSTRAINT [DF_gTipoTransaccionConfig_vigencia] DEFAULT ((0)) NOT NULL,
    [pDesEditable]           BIT           CONSTRAINT [DF_gTipoTransaccionConfig_pDesEditable] DEFAULT ((0)) NOT NULL,
    [UmedidaEditable]        BIT           CONSTRAINT [DF_gTipoTransaccionConfig_UmedidaEditable] DEFAULT ((0)) NOT NULL,
    [estudioCompra]          BIT           CONSTRAINT [DF_gTipoTransaccionConfig_estudioCompra] DEFAULT ((0)) NOT NULL,
    [registroProveedor]      BIT           CONSTRAINT [DF_gTipoTransaccionConfig_registroProveedor] DEFAULT ((0)) NOT NULL,
    [fechaActual]            BIT           CONSTRAINT [DF_gTipoTransaccionConfig_fechaActual] DEFAULT ((0)) NOT NULL,
    [manejaBascula]          BIT           CONSTRAINT [DF_gTipoTransaccionConfig_manejaBascula] DEFAULT ((0)) NOT NULL,
    [mTipoLiquidacionNomina] BIT           NULL,
    [tipoLiquidacionNomina]  VARCHAR (50)  NULL,
    CONSTRAINT [PK_gTipoTransaccionConfig1] PRIMARY KEY CLUSTERED ([empresa] ASC, [tipoTransaccion] ASC),
    CONSTRAINT [FK_gTipoTransaccionConfig_gEmpresa] FOREIGN KEY ([empresa]) REFERENCES [dbo].[gEmpresa] ([id]),
    CONSTRAINT [FK_gTipoTransaccionConfig_gTipoTransaccion] FOREIGN KEY ([empresa], [tipoTransaccion]) REFERENCES [dbo].[gTipoTransaccion] ([empresa], [codigo])
);

