CREATE TABLE [dbo].[nContratos] (
    [empresa]                  INT            NOT NULL,
    [id]                       INT            NOT NULL,
    [codigoTercero]            VARCHAR (50)   NOT NULL,
    [tercero]                  INT            NOT NULL,
    [cargo]                    VARCHAR (50)   NULL,
    [banco]                    VARCHAR (50)   NULL,
    [tipoContizante]           VARCHAR (50)   NULL,
    [motivoRetiro]             VARCHAR (50)   NULL,
    [turno]                    VARCHAR (50)   NULL,
    [departamento]             VARCHAR (50)   NULL,
    [ccosto]                   VARCHAR (50)   NULL,
    [tipoNomina]               VARCHAR (50)   NULL,
    [tiempoBasico]             VARCHAR (50)   NULL,
    [entidadPension]           VARCHAR (50)   NULL,
    [entidadEps]               VARCHAR (50)   NULL,
    [entidadCesantias]         VARCHAR (50)   NULL,
    [entidadCaja]              VARCHAR (50)   NULL,
    [entidadArp]               VARCHAR (50)   NULL,
    [entidadSena]              VARCHAR (50)   NULL,
    [entidadIcbf]              VARCHAR (50)   NULL,
    [fechaIngreso]             DATETIME       NULL,
    [fechaRetiro]              DATETIME       NULL,
    [fechaContratoHasta]       DATETIME       NULL,
    [fechaPrimaHasta]          DATETIME       NULL,
    [fechaVacacionesHasta]     DATETIME       NULL,
    [fechaUltimoAumento]       DATETIME       NULL,
    [fechaUltimoVacaciones]    DATETIME       NULL,
    [fechaUltimaPension]       DATETIME       NULL,
    [fechaUltimoCesantias]     DATETIME       NULL,
    [fechaContratoLey50]       DATETIME       NULL,
    [salario]                  MONEY          NOT NULL,
    [salarioAnterior]          MONEY          NOT NULL,
    [valorDeducibleRete]       MONEY          NOT NULL,
    [valorCesantiasCongeladas] MONEY          NOT NULL,
    [valorCesantiasRetiradas]  MONEY          NOT NULL,
    [valorOtrosSalud]          MONEY          NOT NULL,
    [valorSaludObligatoria]    MONEY          NOT NULL,
    [cantidadHoras]            DECIMAL (9, 6) NOT NULL,
    [pRetencion]               DECIMAL (9, 6) NOT NULL,
    [pTiempoLaborado]          DECIMAL (9, 6) NOT NULL,
    [diasPagadosVaciones]      DECIMAL (9, 6) NOT NULL,
    [personaCargo]             INT            NULL,
    [cuentaBancaria]           VARCHAR (50)   NULL,
    [formaPago]                VARCHAR (50)   NULL,
    [regimenLaboral]           INT            NULL,
    [auxilioTransporte]        INT            NULL,
    [procediimentoRete]        INT            NULL,
    [pactoColectivo]           BIT            NULL,
    [deducible]                VARCHAR (50)   NULL,
    [otrosSalud]               VARCHAR (50)   NULL,
    [salarioIntegral]          BIT            NULL,
    [tipoCuenta]               VARCHAR (50)   NULL,
    [claseContrato]            VARCHAR (50)   NOT NULL,
    [terminoContrato]          VARCHAR (1)    NOT NULL,
    [foto]                     INT            NULL,
    [observacion]              VARCHAR (50)   NULL,
    [activo]                   BIT            NOT NULL,
    [valorPrepagada]           MONEY          NOT NULL,
    [valorDependientes]        MONEY          NOT NULL,
    [fechaRegistro]            DATETIME       NOT NULL,
    [usuario]                  VARCHAR (50)   NOT NULL,
    [fechaActualizacion]       DATETIME       NULL,
    [usuarioActualizacion]     VARCHAR (50)   NULL,
    [ley50]                    BIT            CONSTRAINT [DF_nContratos_ley50] DEFAULT ((0)) NOT NULL,
    [centroTrabajo]            VARCHAR (50)   NOT NULL,
    [diasContrato]             INT            NOT NULL,
    [mSindicato]               BIT            NULL,
    [mFondoEmpleado]           BIT            NULL,
    [entidadFondoEmpleado]     VARCHAR (50)   NULL,
    [entidadSindicato]         VARCHAR (50)   NULL,
    [pFondoEmpleado]           FLOAT (53)     NULL,
    [pSindicato]               FLOAT (53)     NULL,
    [subTipoCotizante]         VARCHAR (50)   NULL,
    [entidadSaludAdicional]    VARCHAR (50)   NULL,
    [manejaDestajo]            BIT            NULL,
    [grupoLaborDestajo]        VARCHAR (50)   NULL,
    [cantidadDestajo]          INT            NULL,
    CONSTRAINT [PK_nContratos] PRIMARY KEY CLUSTERED ([empresa] ASC, [id] ASC, [codigoTercero] ASC, [tercero] ASC),
    CONSTRAINT [FK_nContratos_cCentrosCosto] FOREIGN KEY ([empresa], [ccosto]) REFERENCES [dbo].[cCentrosCosto] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_gFormaPago] FOREIGN KEY ([empresa], [formaPago]) REFERENCES [dbo].[gFormaPago] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nCargo] FOREIGN KEY ([empresa], [cargo]) REFERENCES [dbo].[nCargo] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nClaseContrato] FOREIGN KEY ([empresa], [claseContrato]) REFERENCES [dbo].[nClaseContrato] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nDepartamento] FOREIGN KEY ([empresa], [departamento]) REFERENCES [dbo].[nDepartamento] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nEntidadAfc] FOREIGN KEY ([empresa], [entidadCesantias]) REFERENCES [dbo].[nEntidadAfc] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nEntidadCaja] FOREIGN KEY ([empresa], [entidadCaja]) REFERENCES [dbo].[nEntidadCaja] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nEntidadEps] FOREIGN KEY ([empresa], [entidadEps]) REFERENCES [dbo].[nEntidadEps] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nEntidadFondoPension] FOREIGN KEY ([empresa], [entidadPension]) REFERENCES [dbo].[nEntidadFondoPension] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nFuncionario] FOREIGN KEY ([empresa], [tercero]) REFERENCES [dbo].[nFuncionario] ([empresa], [tercero]),
    CONSTRAINT [FK_nContratos_nSubTipoCotizante] FOREIGN KEY ([empresa], [subTipoCotizante]) REFERENCES [dbo].[nSubTipoCotizante] ([empresa], [codigo]),
    CONSTRAINT [FK_nContratos_nTipoCotizante] FOREIGN KEY ([empresa], [tipoContizante]) REFERENCES [dbo].[nTipoCotizante] ([empresa], [codigo])
);

