CREATE TABLE [dbo].[nConcepto] (
    [empresa]              INT             NOT NULL,
    [codigo]               VARCHAR (50)    NOT NULL,
    [descripcion]          VARCHAR (550)   NOT NULL,
    [abreviatura]          VARCHAR (20)    NOT NULL,
    [signo]                INT             NOT NULL,
    [tipoLiquidacion]      INT             NOT NULL,
    [base]                 VARCHAR (50)    NULL,
    [porcentaje]           DECIMAL (18, 3) NOT NULL,
    [valor]                MONEY           NOT NULL,
    [valorMinimo]          MONEY           NOT NULL,
    [basePrimas]           BIT             NOT NULL,
    [baseCajaCompensacion] BIT             NOT NULL,
    [baseCesantias]        BIT             NOT NULL,
    [baseVacaciones]       BIT             NOT NULL,
    [baseIntereses]        BIT             NOT NULL,
    [baseSeguridadSocial]  BIT             NOT NULL,
    [controlaSaldo]        BIT             NOT NULL,
    [manejaRango]          BIT             NOT NULL,
    [ingresoGravado]       BIT             NOT NULL,
    [controlConcepto]      INT             NOT NULL,
    [activo]               BIT             NOT NULL,
    [fechaRegistro]        DATETIME        NOT NULL,
    [usuarioRegistro]      VARCHAR (50)    NOT NULL,
    [validaPorcentaje]     BIT             CONSTRAINT [DF_nConcepto_validaPorcentaje] DEFAULT ((0)) NOT NULL,
    [fijo]                 BIT             NOT NULL,
    [baseEmbargo]          BIT             NULL,
    [prioridad]            INT             NULL,
    [descuentaDomingo]     BIT             CONSTRAINT [DF_nConcepto_descuentaDomingo] DEFAULT ((0)) NOT NULL,
    [descuentaTransporte]  BIT             CONSTRAINT [DF_nConcepto_descuentaTransporte] DEFAULT ((0)) NOT NULL,
    [mostrarFecha]         BIT             CONSTRAINT [DF_nConcepto_mostrarFecha] DEFAULT ((0)) NOT NULL,
    [noMostrar]            BIT             CONSTRAINT [DF_nConcepto_noMostrar] DEFAULT ((0)) NOT NULL,
    [mostrarDetalle]       BIT             NOT NULL,
    [ausentismo]           BIT             CONSTRAINT [DF_nConcepto_ausentismo] DEFAULT ((0)) NOT NULL,
    [prestacionSocial]     BIT             NULL,
    [sumaPrestacionSocial] BIT             NULL,
    [mostrarCantidad]      BIT             NULL,
    [noMes]                INT             NULL,
    CONSTRAINT [PK_nConcepto] PRIMARY KEY CLUSTERED ([empresa] ASC, [codigo] ASC)
);

