CREATE TABLE [dbo].[nLiquidacionNominaDetalle] (
    [empresa]              INT             NOT NULL,
    [tipo]                 VARCHAR (50)    NOT NULL,
    [numero]               VARCHAR (50)    NOT NULL,
    [año]                  INT             NOT NULL,
    [mes]                  INT             NOT NULL,
    [registro]             INT             NOT NULL,
    [noPeriodo]            INT             NOT NULL,
    [tercero]              INT             NOT NULL,
    [concepto]             VARCHAR (50)    NOT NULL,
    [fechaInicial]         DATE            NULL,
    [fechaFinal]           DATE            NULL,
    [ccosto]               VARCHAR (50)    NULL,
    [departamento]         VARCHAR (50)    NULL,
    [cantidad]             DECIMAL (18, 3) NULL,
    [porcentaje]           DECIMAL (18, 3) NULL,
    [valorUnitario]        MONEY           NULL,
    [valorTotal]           MONEY           NULL,
    [signo]                INT             NULL,
    [saldo]                MONEY           NULL,
    [noDias]               INT             NULL,
    [entidad]              INT             NULL,
    [contrato]             INT             NULL,
    [basePrimas]           BIT             NOT NULL,
    [baseCajaCompensacion] BIT             NOT NULL,
    [baseCesantias]        BIT             NOT NULL,
    [baseVacaciones]       BIT             NOT NULL,
    [baseIntereses]        BIT             NOT NULL,
    [baseSeguridadSocial]  BIT             NOT NULL,
    [manejaRango]          BIT             NOT NULL,
    [baseEmbargo]          BIT             NOT NULL,
    [noPrestamo]           VARCHAR (50)    NULL,
    [cantidadR]            DECIMAL (18, 3) NULL,
    [valorTotalR]          MONEY           NULL,
    [fecha]                DATE            NULL,
    [tipoConcepto]         VARCHAR (50)    NULL,
    [desTipoConcepto]      VARCHAR (200)   NULL,
    CONSTRAINT [PK_nLiquidacionNominaDetalle] PRIMARY KEY CLUSTERED ([empresa] ASC, [tipo] ASC, [numero] ASC, [año] ASC, [mes] ASC, [registro] ASC),
    CONSTRAINT [FK_nLiquidacionNominaDetalle_cCentrosCosto] FOREIGN KEY ([empresa], [ccosto]) REFERENCES [dbo].[cCentrosCosto] ([empresa], [codigo]),
    CONSTRAINT [FK_nLiquidacionNominaDetalle_cTercero] FOREIGN KEY ([empresa], [tercero]) REFERENCES [dbo].[cTercero] ([empresa], [id]),
    CONSTRAINT [FK_nLiquidacionNominaDetalle_nConcepto] FOREIGN KEY ([empresa], [concepto]) REFERENCES [dbo].[nConcepto] ([empresa], [codigo]),
    CONSTRAINT [FK_nLiquidacionNominaDetalle_nLiquidacionNomina] FOREIGN KEY ([empresa], [tipo], [numero], [año], [mes]) REFERENCES [dbo].[nLiquidacionNomina] ([empresa], [tipo], [numero], [año], [mes]),
    CONSTRAINT [FK_nLiquidacionNominaDetalle_nPeriodoDetalle] FOREIGN KEY ([empresa], [año], [mes], [noPeriodo]) REFERENCES [dbo].[nPeriodoDetalle] ([empresa], [año], [mes], [noPeriodo])
);

