CREATE TABLE [dbo].[nParametrosGeneral] (
    [empresa]              INT          NOT NULL,
    [noSalarioIntegral]    INT          NOT NULL,
    [jornadaDiaria]        INT          NOT NULL,
    [tipoJornadaDiaria]    VARCHAR (2)  NOT NULL,
    [horaInicioDiurna]     INT          NOT NULL,
    [horaInicioNocturna]   INT          NOT NULL,
    [fechaUlrimaCesantias] DATE         NOT NULL,
    [HO]                   VARCHAR (50) NULL,
    [HRN]                  VARCHAR (50) NULL,
    [HEN]                  VARCHAR (50) NULL,
    [HED]                  VARCHAR (50) NULL,
    [HD]                   VARCHAR (50) NULL,
    [HF]                   VARCHAR (50) NULL,
    [HRF]                  VARCHAR (50) NULL,
    [HENF]                 VARCHAR (50) NULL,
    [HEDF]                 VARCHAR (50) NULL,
    [sueldo]               VARCHAR (50) NULL,
    [jornales]             VARCHAR (50) NULL,
    [cesantias]            VARCHAR (50) NULL,
    [intereses]            VARCHAR (50) NULL,
    [vacaciones]           VARCHAR (50) NULL,
    [primas]               VARCHAR (50) NULL,
    [salarioIntegral]      VARCHAR (50) NULL,
    [permisos]             VARCHAR (50) NULL,
    [subsidioTransporte]   VARCHAR (50) NULL,
    [retroactivo]          VARCHAR (50) NULL,
    [retencion]            VARCHAR (50) NULL,
    [suspenciones]         VARCHAR (50) NULL,
    [incapacidades]        VARCHAR (50) NULL,
    [cajaCompensacion]     VARCHAR (50) NULL,
    [sena]                 VARCHAR (50) NULL,
    [ICBF]                 VARCHAR (50) NULL,
    [ARP]                  VARCHAR (50) NULL,
    [indemnizacion]        VARCHAR (50) NULL,
    [EM]                   VARCHAR (50) NULL,
    [IVM]                  VARCHAR (50) NULL,
    [ATEP]                 VARCHAR (50) NULL,
    [fondoSolidaridad]     VARCHAR (50) NULL,
    [licRemunerado]        VARCHAR (50) NULL,
    [licNoRemunerado]      VARCHAR (50) NULL,
    [PrimasExtralegales]   VARCHAR (50) NULL,
    [anticipoCesantias]    VARCHAR (50) NULL,
    [fechaRegistro]        DATETIME     NOT NULL,
    [fechaEdicion]         DATETIME     NULL,
    [usuarioRegistro]      VARCHAR (50) NOT NULL,
    [usuarioEdicion]       VARCHAR (50) NULL,
    [salud]                VARCHAR (50) NULL,
    [pension]              VARCHAR (50) NULL,
    [embargos]             VARCHAR (50) NULL,
    [ganaDomingo]          VARCHAR (50) NULL,
    [pGanaDomingo]         BIT          CONSTRAINT [DF_nParametrosGeneral_pGanaDomingo] DEFAULT ((0)) NOT NULL,
    [HEDD]                 VARCHAR (50) NULL,
    [HEND]                 VARCHAR (50) NULL,
    [HRD]                  VARCHAR (50) NULL,
    [fondoEmpleado]        VARCHAR (50) NULL,
    [sindicato]            VARCHAR (50) NULL,
    [diasVacaciones]       INT          NULL,
    [pagoFestivo]          VARCHAR (50) NULL,
    [aprendizSena]         VARCHAR (50) NULL,
    [horaFinalDiurna]      INT          NULL,
    [horaFinalNocturna]    INT          NULL,
    [noSMLVSenaICBF]       INT          NULL,
    [promedioFestivo]      BIT          CONSTRAINT [DF_nParametrosGeneral_promedioFestivo] DEFAULT ((0)) NOT NULL,
    [paga31]               BIT          NULL,
    CONSTRAINT [PK_nParametrosGeneral] PRIMARY KEY CLUSTERED ([empresa] ASC)
);

