CREATE TABLE [dbo].[nPrestamo] (
    [empresa]         INT            NOT NULL,
    [codigo]          VARCHAR (50)   NOT NULL,
    [fecha]           DATE           NULL,
    [ccosto]          VARCHAR (50)   NOT NULL,
    [empleado]        INT            NOT NULL,
    [concepto]        VARCHAR (50)   NOT NULL,
    [año]             INT            NOT NULL,
    [mes]             INT            NOT NULL,
    [periodoInicial]  INT            NOT NULL,
    [valor]           MONEY          NOT NULL,
    [cuotas]          INT            NOT NULL,
    [valorCuotas]     MONEY          NOT NULL,
    [cuotasPendiente] INT            NOT NULL,
    [valorSaldo]      MONEY          NOT NULL,
    [frecuencia]      INT            NOT NULL,
    [observacion]     VARCHAR (5500) NOT NULL,
    [usuarioRegistro] VARCHAR (50)   NOT NULL,
    [fechaRegistro]   DATETIME       NOT NULL,
    [liquidado]       BIT            NOT NULL,
    [formaPago]       VARCHAR (50)   NOT NULL,
    [docRef]          VARCHAR (200)  NOT NULL,
    CONSTRAINT [PK_nPrestamo] PRIMARY KEY CLUSTERED ([empresa] ASC, [codigo] ASC)
);

