CREATE TABLE [dbo].[nVacaciones] (
    [empresa]        INT             NOT NULL,
    [periodoInicial] DATE            NOT NULL,
    [periodoFinal]   DATE            NOT NULL,
    [empleado]       INT             NOT NULL,
    [registro]       INT             NOT NULL,
    [tipo]           VARCHAR (10)    NOT NULL,
    [fechaSalida]    DATE            NULL,
    [fechaRetorno]   DATE            NULL,
    [diasCausados]   INT             NOT NULL,
    [diasTomados]    INT             NOT NULL,
    [diasPendientes] INT             NOT NULL,
    [diasPagados]    INT             NOT NULL,
    [valorPagado]    DECIMAL (18, 2) NOT NULL,
    [valorBase]      DECIMAL (18, 2) NOT NULL,
    [usuario]        VARCHAR (50)    NOT NULL,
    [fechaRegistro]  DATETIME        NOT NULL,
    [observaciones]  VARCHAR (500)   NULL,
    [anulado]        BIT             CONSTRAINT [DF_nVacaciones_anulado] DEFAULT ((0)) NOT NULL,
    [fechaAnulado]   DATETIME        NULL,
    [usuarioAnulado] VARCHAR (50)    NULL,
    [ejecutado]      BIT             CONSTRAINT [DF_nVacaciones_ejecutado] DEFAULT ((0)) NOT NULL,
    [pagaNomina]     BIT             CONSTRAINT [DF_nVacaciones_pagaNomina] DEFAULT ((0)) NOT NULL,
    [acumulada]      BIT             NULL,
    [liquidada]      BIT             NULL,
    [año]            INT             NULL,
    [mes]            INT             NULL,
    [periodo]        INT             NULL,
    [añoPago]        INT             NULL,
    CONSTRAINT [PK_nVacaciones] PRIMARY KEY CLUSTERED ([empresa] ASC, [periodoInicial] ASC, [periodoFinal] ASC, [empleado] ASC, [registro] ASC),
    CONSTRAINT [FK_nVacaciones_cTercero] FOREIGN KEY ([empresa], [empleado]) REFERENCES [dbo].[cTercero] ([empresa], [id])
);

