CREATE TABLE [dbo].[tmpliquidacionNominaVacaciones] (
    [empresa]             INT             NULL,
    [tercero]             VARCHAR (50)    NULL,
    [ccosto]              VARCHAR (50)    NULL,
    [fecha]               DATE            NULL,
    [departamento]        VARCHAR (50)    NULL,
    [concepto]            VARCHAR (50)    NULL,
    [año]                 INT             NULL,
    [mes]                 INT             NULL,
    [noPeriodo]           INT             NULL,
    [cantidad]            DECIMAL (18, 3) NULL,
    [porcentaje]          DECIMAL (18, 3) NULL,
    [valorUnitario]       MONEY           NULL,
    [valorTotal]          MONEY           NULL,
    [signo]               INT             NULL,
    [saldo]               MONEY           NULL,
    [noDias]              INT             NULL,
    [fechaInical]         DATE            NULL,
    [fechaFinal]          DATE            NULL,
    [baseSeguridadSocial] BIT             NULL,
    [baseEmbargos]        BIT             NULL,
    [entidad]             VARCHAR (50)    NULL,
    [noPrestamo]          VARCHAR (50)    NULL
);

