CREATE TABLE [dbo].[tmpliquidacionNomina] (
    [empresa]             INT           NULL,
    [tercero]             VARCHAR (50)  NULL,
    [ccosto]              VARCHAR (50)  NULL,
    [fecha]               DATE          NULL,
    [departamento]        VARCHAR (50)  NULL,
    [concepto]            VARCHAR (50)  NULL,
    [año]                 INT           NULL,
    [mes]                 INT           NULL,
    [noPeriodo]           INT           NULL,
    [cantidad]            FLOAT (53)    NULL,
    [porcentaje]          FLOAT (53)    NULL,
    [valorUnitario]       FLOAT (53)    NULL,
    [valorTotal]          FLOAT (53)    NULL,
    [signo]               INT           NULL,
    [saldo]               FLOAT (53)    NULL,
    [noDias]              FLOAT (53)    NULL,
    [fechaInical]         DATE          NULL,
    [fechaFinal]          DATE          NULL,
    [baseSeguridadSocial] BIT           NULL,
    [baseEmbargos]        BIT           NULL,
    [entidad]             VARCHAR (50)  NULL,
    [cantidadPadelma]     FLOAT (53)    NULL,
    [valorPadelma]        FLOAT (53)    NULL,
    [noContrato]          INT           NULL,
    [noPrestamo]          VARCHAR (50)  NULL,
    [tipoConcepto]        VARCHAR (50)  NULL,
    [desTipoConcepto]     VARCHAR (200) NULL
);

