//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaInfos.SeguridadInfos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx", ConfigurationName="SeguridadInfos.SecuritySoap")]
    public interface SecuritySoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/Security/Security.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/ValidarUsuario", ReplyAction="*")]
        NominaInfos.SeguridadInfos.ValidarUsuarioResponse ValidarUsuario(NominaInfos.SeguridadInfos.ValidarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.ValidarUsuarioResponse> ValidarUsuarioAsync(NominaInfos.SeguridadInfos.ValidarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/Security/Security.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/InsertaLog", ReplyAction="*")]
        NominaInfos.SeguridadInfos.InsertaLogResponse InsertaLog(NominaInfos.SeguridadInfos.InsertaLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/InsertaLog", ReplyAction="*")]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.InsertaLogResponse> InsertaLogAsync(NominaInfos.SeguridadInfos.InsertaLogRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/Security/Security.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/VerificaAccesoPagina", ReplyAction="*")]
        NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse VerificaAccesoPagina(NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/VerificaAccesoPagina", ReplyAction="*")]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse> VerificaAccesoPaginaAsync(NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/Security/Security.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/VerificaAccesoOperacion", ReplyAction="*")]
        NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse VerificaAccesoOperacion(NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/VerificaAccesoOperacion", ReplyAction="*")]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse> VerificaAccesoOperacionAsync(NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/Security/Security.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/RetornaEmpresa", ReplyAction="*")]
        NominaInfos.SeguridadInfos.RetornaEmpresaResponse RetornaEmpresa(NominaInfos.SeguridadInfos.RetornaEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Security/Security.asmx/RetornaEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.RetornaEmpresaResponse> RetornaEmpresaAsync(NominaInfos.SeguridadInfos.RetornaEmpresaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuario", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.ValidarUsuarioRequestBody Body;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(NominaInfos.SeguridadInfos.ValidarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class ValidarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idSys;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sitio;
        
        public ValidarUsuarioRequestBody() {
        }
        
        public ValidarUsuarioRequestBody(string usuario, string idSys, string sitio) {
            this.usuario = usuario;
            this.idSys = idSys;
            this.sitio = sitio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuarioResponse", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.ValidarUsuarioResponseBody Body;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(NominaInfos.SeguridadInfos.ValidarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class ValidarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidarUsuarioResult;
        
        public ValidarUsuarioResponseBody() {
        }
        
        public ValidarUsuarioResponseBody(int ValidarUsuarioResult) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaLog", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.InsertaLogRequestBody Body;
        
        public InsertaLogRequest() {
        }
        
        public InsertaLogRequest(NominaInfos.SeguridadInfos.InsertaLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class InsertaLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string operacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string entidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int empresa;
        
        public InsertaLogRequestBody() {
        }
        
        public InsertaLogRequestBody(string usuario, string operacion, string entidad, string estado, string mensaje, string ip, int empresa) {
            this.usuario = usuario;
            this.operacion = operacion;
            this.entidad = entidad;
            this.estado = estado;
            this.mensaje = mensaje;
            this.ip = ip;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaLogResponse", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.InsertaLogResponseBody Body;
        
        public InsertaLogResponse() {
        }
        
        public InsertaLogResponse(NominaInfos.SeguridadInfos.InsertaLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertaLogResponseBody {
        
        public InsertaLogResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaAccesoPaginaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaAccesoPagina", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequestBody Body;
        
        public VerificaAccesoPaginaRequest() {
        }
        
        public VerificaAccesoPaginaRequest(NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class VerificaAccesoPaginaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pagina;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int empresa;
        
        public VerificaAccesoPaginaRequestBody() {
        }
        
        public VerificaAccesoPaginaRequestBody(string usuario, string sitio, string pagina, int empresa) {
            this.usuario = usuario;
            this.sitio = sitio;
            this.pagina = pagina;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaAccesoPaginaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaAccesoPaginaResponse", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponseBody Body;
        
        public VerificaAccesoPaginaResponse() {
        }
        
        public VerificaAccesoPaginaResponse(NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class VerificaAccesoPaginaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VerificaAccesoPaginaResult;
        
        public VerificaAccesoPaginaResponseBody() {
        }
        
        public VerificaAccesoPaginaResponseBody(int VerificaAccesoPaginaResult) {
            this.VerificaAccesoPaginaResult = VerificaAccesoPaginaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaAccesoOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaAccesoOperacion", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequestBody Body;
        
        public VerificaAccesoOperacionRequest() {
        }
        
        public VerificaAccesoOperacionRequest(NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class VerificaAccesoOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pagina;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string operacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int empresa;
        
        public VerificaAccesoOperacionRequestBody() {
        }
        
        public VerificaAccesoOperacionRequestBody(string usuario, string sitio, string pagina, string operacion, int empresa) {
            this.usuario = usuario;
            this.sitio = sitio;
            this.pagina = pagina;
            this.operacion = operacion;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaAccesoOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaAccesoOperacionResponse", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponseBody Body;
        
        public VerificaAccesoOperacionResponse() {
        }
        
        public VerificaAccesoOperacionResponse(NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class VerificaAccesoOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VerificaAccesoOperacionResult;
        
        public VerificaAccesoOperacionResponseBody() {
        }
        
        public VerificaAccesoOperacionResponseBody(int VerificaAccesoOperacionResult) {
            this.VerificaAccesoOperacionResult = VerificaAccesoOperacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaEmpresa", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.RetornaEmpresaRequestBody Body;
        
        public RetornaEmpresaRequest() {
        }
        
        public RetornaEmpresaRequest(NominaInfos.SeguridadInfos.RetornaEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class RetornaEmpresaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public RetornaEmpresaRequestBody() {
        }
        
        public RetornaEmpresaRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaEmpresaResponse", Namespace="http://tempuri.org/Security/Security.asmx", Order=0)]
        public NominaInfos.SeguridadInfos.RetornaEmpresaResponseBody Body;
        
        public RetornaEmpresaResponse() {
        }
        
        public RetornaEmpresaResponse(NominaInfos.SeguridadInfos.RetornaEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Security/Security.asmx")]
    public partial class RetornaEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RetornaEmpresaResult;
        
        public RetornaEmpresaResponseBody() {
        }
        
        public RetornaEmpresaResponseBody(int RetornaEmpresaResult) {
            this.RetornaEmpresaResult = RetornaEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecuritySoapChannel : NominaInfos.SeguridadInfos.SecuritySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuritySoapClient : System.ServiceModel.ClientBase<NominaInfos.SeguridadInfos.SecuritySoap>, NominaInfos.SeguridadInfos.SecuritySoap {
        
        public SecuritySoapClient() {
        }
        
        public SecuritySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NominaInfos.SeguridadInfos.ValidarUsuarioResponse NominaInfos.SeguridadInfos.SecuritySoap.ValidarUsuario(NominaInfos.SeguridadInfos.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public int ValidarUsuario(string usuario, string idSys, string sitio) {
            NominaInfos.SeguridadInfos.ValidarUsuarioRequest inValue = new NominaInfos.SeguridadInfos.ValidarUsuarioRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.idSys = idSys;
            inValue.Body.sitio = sitio;
            NominaInfos.SeguridadInfos.ValidarUsuarioResponse retVal = ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).ValidarUsuario(inValue);
            return retVal.Body.ValidarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.ValidarUsuarioResponse> NominaInfos.SeguridadInfos.SecuritySoap.ValidarUsuarioAsync(NominaInfos.SeguridadInfos.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.ValidarUsuarioResponse> ValidarUsuarioAsync(string usuario, string idSys, string sitio) {
            NominaInfos.SeguridadInfos.ValidarUsuarioRequest inValue = new NominaInfos.SeguridadInfos.ValidarUsuarioRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.idSys = idSys;
            inValue.Body.sitio = sitio;
            return ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).ValidarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NominaInfos.SeguridadInfos.InsertaLogResponse NominaInfos.SeguridadInfos.SecuritySoap.InsertaLog(NominaInfos.SeguridadInfos.InsertaLogRequest request) {
            return base.Channel.InsertaLog(request);
        }
        
        public void InsertaLog(string usuario, string operacion, string entidad, string estado, string mensaje, string ip, int empresa) {
            NominaInfos.SeguridadInfos.InsertaLogRequest inValue = new NominaInfos.SeguridadInfos.InsertaLogRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.InsertaLogRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.operacion = operacion;
            inValue.Body.entidad = entidad;
            inValue.Body.estado = estado;
            inValue.Body.mensaje = mensaje;
            inValue.Body.ip = ip;
            inValue.Body.empresa = empresa;
            NominaInfos.SeguridadInfos.InsertaLogResponse retVal = ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).InsertaLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.InsertaLogResponse> NominaInfos.SeguridadInfos.SecuritySoap.InsertaLogAsync(NominaInfos.SeguridadInfos.InsertaLogRequest request) {
            return base.Channel.InsertaLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.InsertaLogResponse> InsertaLogAsync(string usuario, string operacion, string entidad, string estado, string mensaje, string ip, int empresa) {
            NominaInfos.SeguridadInfos.InsertaLogRequest inValue = new NominaInfos.SeguridadInfos.InsertaLogRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.InsertaLogRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.operacion = operacion;
            inValue.Body.entidad = entidad;
            inValue.Body.estado = estado;
            inValue.Body.mensaje = mensaje;
            inValue.Body.ip = ip;
            inValue.Body.empresa = empresa;
            return ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).InsertaLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse NominaInfos.SeguridadInfos.SecuritySoap.VerificaAccesoPagina(NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest request) {
            return base.Channel.VerificaAccesoPagina(request);
        }
        
        public int VerificaAccesoPagina(string usuario, string sitio, string pagina, int empresa) {
            NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest inValue = new NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.sitio = sitio;
            inValue.Body.pagina = pagina;
            inValue.Body.empresa = empresa;
            NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse retVal = ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).VerificaAccesoPagina(inValue);
            return retVal.Body.VerificaAccesoPaginaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse> NominaInfos.SeguridadInfos.SecuritySoap.VerificaAccesoPaginaAsync(NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest request) {
            return base.Channel.VerificaAccesoPaginaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoPaginaResponse> VerificaAccesoPaginaAsync(string usuario, string sitio, string pagina, int empresa) {
            NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest inValue = new NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.VerificaAccesoPaginaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.sitio = sitio;
            inValue.Body.pagina = pagina;
            inValue.Body.empresa = empresa;
            return ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).VerificaAccesoPaginaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse NominaInfos.SeguridadInfos.SecuritySoap.VerificaAccesoOperacion(NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest request) {
            return base.Channel.VerificaAccesoOperacion(request);
        }
        
        public int VerificaAccesoOperacion(string usuario, string sitio, string pagina, string operacion, int empresa) {
            NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest inValue = new NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.sitio = sitio;
            inValue.Body.pagina = pagina;
            inValue.Body.operacion = operacion;
            inValue.Body.empresa = empresa;
            NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse retVal = ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).VerificaAccesoOperacion(inValue);
            return retVal.Body.VerificaAccesoOperacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse> NominaInfos.SeguridadInfos.SecuritySoap.VerificaAccesoOperacionAsync(NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest request) {
            return base.Channel.VerificaAccesoOperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.VerificaAccesoOperacionResponse> VerificaAccesoOperacionAsync(string usuario, string sitio, string pagina, string operacion, int empresa) {
            NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest inValue = new NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.VerificaAccesoOperacionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.sitio = sitio;
            inValue.Body.pagina = pagina;
            inValue.Body.operacion = operacion;
            inValue.Body.empresa = empresa;
            return ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).VerificaAccesoOperacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NominaInfos.SeguridadInfos.RetornaEmpresaResponse NominaInfos.SeguridadInfos.SecuritySoap.RetornaEmpresa(NominaInfos.SeguridadInfos.RetornaEmpresaRequest request) {
            return base.Channel.RetornaEmpresa(request);
        }
        
        public int RetornaEmpresa(string usuario) {
            NominaInfos.SeguridadInfos.RetornaEmpresaRequest inValue = new NominaInfos.SeguridadInfos.RetornaEmpresaRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.RetornaEmpresaRequestBody();
            inValue.Body.usuario = usuario;
            NominaInfos.SeguridadInfos.RetornaEmpresaResponse retVal = ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).RetornaEmpresa(inValue);
            return retVal.Body.RetornaEmpresaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.RetornaEmpresaResponse> NominaInfos.SeguridadInfos.SecuritySoap.RetornaEmpresaAsync(NominaInfos.SeguridadInfos.RetornaEmpresaRequest request) {
            return base.Channel.RetornaEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NominaInfos.SeguridadInfos.RetornaEmpresaResponse> RetornaEmpresaAsync(string usuario) {
            NominaInfos.SeguridadInfos.RetornaEmpresaRequest inValue = new NominaInfos.SeguridadInfos.RetornaEmpresaRequest();
            inValue.Body = new NominaInfos.SeguridadInfos.RetornaEmpresaRequestBody();
            inValue.Body.usuario = usuario;
            return ((NominaInfos.SeguridadInfos.SecuritySoap)(this)).RetornaEmpresaAsync(inValue);
        }
    }
}
