CREATE TABLE [dbo].[aSanidadDetalle] (
    [empresa]             INT             NOT NULL,
    [tipo]                VARCHAR (50)    NOT NULL,
    [numero]              VARCHAR (50)    NOT NULL,
    [registro]            INT             NOT NULL,
    [fecha]               DATE            NOT NULL,
    [linea]               INT             NULL,
    [palma]               INT             NULL,
    [item]                VARCHAR (50)    NOT NULL,
    [cantidad]            DECIMAL (18, 3) NULL,
    [uMedida]             VARCHAR (50)    NULL,
    [detalle]             VARCHAR (550)   NOT NULL,
    [ejecutado]           BIT             NULL,
    [fechaEjecutado]      DATETIME        NULL,
    [usuarioEjecturado]   DATETIME        NULL,
    [referenciaDetalle]   VARCHAR (50)    NULL,
    [grupoCaracteristica] INT             NULL,
    [caracteristica]      INT             NULL,
    [naturaleza]          INT             NOT NULL,
    CONSTRAINT [PK_aSanidadDetalle] PRIMARY KEY CLUSTERED ([empresa] ASC, [tipo] ASC, [numero] ASC, [registro] ASC),
    CONSTRAINT [FK_aSanidadDetalle_aCaracteristica1] FOREIGN KEY ([empresa], [caracteristica]) REFERENCES [dbo].[aCaracteristica] ([empresa], [codigo]),
    CONSTRAINT [FK_aSanidadDetalle_aGrupoCaracteristica] FOREIGN KEY ([empresa], [grupoCaracteristica]) REFERENCES [dbo].[aGrupoCaracteristica] ([empresa], [codigo]),
    CONSTRAINT [FK_aSanidadDetalle_aNovedad] FOREIGN KEY ([empresa], [item]) REFERENCES [dbo].[aNovedad] ([empresa], [codigo]),
    CONSTRAINT [FK_aSanidadDetalle_aSanidad] FOREIGN KEY ([empresa], [tipo], [numero]) REFERENCES [dbo].[aSanidad] ([empresa], [tipo], [numero])
);

