CREATE TABLE [dbo].[nParametrosAno] (
    [empresa]                   INT             NOT NULL,
    [ano]                       INT             NOT NULL,
    [fechaRegistro]             DATETIME        NOT NULL,
    [usuario]                   VARCHAR (30)    NOT NULL,
    [vSalarioMinimo]            MONEY           NOT NULL,
    [vAuxilioTransporte]        MONEY           NOT NULL,
    [vUVT]                      MONEY           NOT NULL,
    [vPatrimonioBruto]          MONEY           NOT NULL,
    [vIngresoBruto]             MONEY           NOT NULL,
    [pExentoRetencion]          DECIMAL (18, 3) NOT NULL,
    [pMaximoaportePension]      DECIMAL (18, 3) NOT NULL,
    [pExentoSalario1393]        DECIMAL (18, 3) NOT NULL,
    [pDependientes]             DECIMAL (18, 3) NOT NULL,
    [vMaximoExento]             MONEY           NOT NULL,
    [vMaxAporteAFC]             MONEY           NOT NULL,
    [vMaxDeducibleVivienda]     MONEY           NOT NULL,
    [vDependientes]             MONEY           NOT NULL,
    [vMinimoingresosDeclarante] MONEY           NOT NULL,
    [vUVT1]                     MONEY           NOT NULL,
    [vUVT2]                     MONEY           NOT NULL,
    [vUVT3]                     MONEY           NOT NULL,
    [vUVT4]                     MONEY           NOT NULL,
    [vUVT5]                     MONEY           NOT NULL,
    [vUVT6]                     MONEY           NOT NULL,
    [cAplicarArt385]            BIT             NOT NULL,
    [cSalarioIntegral]          BIT             NOT NULL,
    [cRestaIncapacidad]         BIT             NOT NULL,
    [cDiasTNL]                  BIT             NOT NULL,
    [observacion]               VARCHAR (5000)  NOT NULL,
    [vMinimoPeriodo]            MONEY           NOT NULL,
    [noSueldoST]                INT             NOT NULL,
    [vMaxPagoSalud]             MONEY           NOT NULL,
    CONSTRAINT [PK_nParametrosAno] PRIMARY KEY CLUSTERED ([empresa] ASC, [ano] ASC) WITH (FILLFACTOR = 90)
);

