CREATE proc [dbo].[spInsertanContratos]
@empresa int,
@id int,
@codigoTercero varchar(50),
@tercero int,
@cargo varchar(50),
@banco varchar(50),
@tipoContizante varchar(50),
@motivoRetiro varchar(50),
@turno varchar(50),
@departamento varchar(50),
@ccosto varchar(50),
@tipoNomina varchar(50),
@tiempoBasico varchar(50),
@entidadPension varchar(50),
@entidadEps varchar(50),
@entidadCesantias varchar(50),
@entidadCaja varchar(50),
@entidadArp varchar(50),
@entidadSena varchar(50),
@entidadIcbf varchar(50),
@fechaIngreso datetime,
@fechaRetiro datetime,
@fechaContratoHasta datetime,
@fechaPrimaHasta datetime,
@fechaVacacionesHasta datetime,
@fechaUltimoAumento datetime,
@fechaUltimoVacaciones datetime,
@fechaUltimaPension datetime,
@fechaUltimoCesantias datetime,
@fechaContratoLey50 datetime,
@salario money,
@salarioAnterior money,
@valorDeducibleRete money,
@valorCesantiasCongeladas money,
@valorCesantiasRetiradas money,
@valorOtrosSalud money,
@valorSaludObligatoria money,
@cantidadHoras decimal(9, 6),
@pRetencion decimal(9, 6),
@pTiempoLaborado decimal(9, 6),
@diasPagadosVaciones decimal(9, 6),
@personaCargo int,
@cuentaBancaria varchar(50),
@formaPago varchar(50),
@regimenLaboral int,
@auxilioTransporte int,
@procediimentoRete int,
@pactoColectivo bit,
@deducible varchar(50),
@otrosSalud varchar(50),
@salarioIntegral bit,
@tipoCuenta varchar(50),
@claseContrato varchar(10),
@terminoContrato varchar(1),
@foto int,
@observacion varchar(50),
@activo bit,
@valorPrepagada money,
@valorDependientes money,
@fechaRegistro datetime,
@usuario varchar(50),
@fechaActualizacion datetime,
@usuarioActualizacion varchar(50),
@ley50 bit,
@subTipoCotizante varchar(50),
@centroTrabajo varchar(50),
@diasContrato int,
@mSindicato bit,	@mFondoEmpleado bit,	@entidadFondoEmpleado varchar(50),	
@entidadSindicato varchar(50),	@pFondoEmpleado float,	@pSindicato float,
@entidadSaludAdicional varchar(50),
@manejaDestajo bit,@cantidadDestajo int,@grupolaborDestajo varchar(50),
@Retorno int output  AS 

begin tran nContratos

insert nContratos
(empresa,
id,
codigoTercero,
tercero,
cargo,
banco,
tipoContizante,
motivoRetiro,
turno,
departamento,
ccosto,
tipoNomina,
tiempoBasico,
entidadPension,
entidadEps,
entidadCesantias,
entidadCaja,
entidadArp,
entidadSena,
entidadIcbf,
fechaIngreso,
fechaRetiro,
fechaContratoHasta,
fechaPrimaHasta,
fechaVacacionesHasta,
fechaUltimoAumento,
fechaUltimoVacaciones,
fechaUltimaPension,
fechaUltimoCesantias,
fechaContratoLey50,
salario,
salarioAnterior,
valorDeducibleRete,
valorCesantiasCongeladas,
valorCesantiasRetiradas,
valorOtrosSalud,
valorSaludObligatoria,
cantidadHoras,
pRetencion,
pTiempoLaborado,
diasPagadosVaciones,
personaCargo,
cuentaBancaria,
formaPago,
regimenLaboral,
auxilioTransporte,
procediimentoRete,
pactoColectivo,
deducible,
otrosSalud,
salarioIntegral,
tipoCuenta,
claseContrato,
terminoContrato,
foto,
observacion,
activo,
valorPrepagada,
valorDependientes,
fechaRegistro,
usuario,
fechaActualizacion,
usuarioActualizacion,
ley50,
centroTrabajo,
diasContrato,
mSindicato ,	mFondoEmpleado ,	entidadFondoEmpleado ,	
entidadSindicato ,	pFondoEmpleado ,	pSindicato,subTipoCotizante,
entidadSaludAdicional,manejaDestajo,grupoLaborDestajo,cantidadDestajo
)
select
@empresa,
@id,
@codigoTercero,
@tercero,
@cargo,
@banco,
@tipoContizante,
@motivoRetiro,
@turno,
@departamento,
@ccosto,
@tipoNomina,
@tiempoBasico,
@entidadPension,
@entidadEps,
@entidadCesantias,
@entidadCaja,
@entidadArp,
@entidadSena,
@entidadIcbf,
@fechaIngreso,
@fechaRetiro,
@fechaContratoHasta,
@fechaPrimaHasta,
@fechaVacacionesHasta,
@fechaUltimoAumento,
@fechaUltimoVacaciones,
@fechaUltimaPension,
@fechaUltimoCesantias,
@fechaContratoLey50,
@salario,
@salarioAnterior,
@valorDeducibleRete,
@valorCesantiasCongeladas,
@valorCesantiasRetiradas,
@valorOtrosSalud,
@valorSaludObligatoria,
@cantidadHoras,
@pRetencion,
@pTiempoLaborado,
@diasPagadosVaciones,
@personaCargo,
@cuentaBancaria,
@formaPago,
@regimenLaboral,
@auxilioTransporte,
@procediimentoRete,
@pactoColectivo,
@deducible,
@otrosSalud,
@salarioIntegral,
@tipoCuenta,
@claseContrato,
@terminoContrato,
@foto,
@observacion,
@activo,
@valorPrepagada,
@valorDependientes,
@fechaRegistro,
@usuario,
@fechaActualizacion,
@usuarioActualizacion,
@ley50,
@centroTrabajo,
@diasContrato,
@mSindicato ,	@mFondoEmpleado ,	@entidadFondoEmpleado ,	
@entidadSindicato ,	@pFondoEmpleado ,	@pSindicato,@subTipoCotizante,@entidadSaludAdicional,
@manejaDestajo,@grupolaborDestajo,@cantidadDestajo

-- actualiza la informacion del contrato cada vez que se inserte uno a contratista falso
update nFuncionario 
set contratista = 0
where tercero = @tercero and empresa =@empresa 

if (@@error = 0 ) begin set
@Retorno = 0 
 commit tran nContratos
  end else begin
  set  @Retorno = 1
   rollback tran nContratos end